- name: "Skapa script f√∂r commit and push repo"
  become: yes
  template:
    src: deploy_cron_commit_and_push_repo.sh.j2
    dest: "{{ webinstance.path }}/deploy/script/commit_and_push-{{ repo.name }}.sh"
    owner: "{{ webinstance.process_user }}"
    group: "{{ webinstance.process_group }}"
    mode: "u=rwx,g=rx,o=r"

    
- name: "Setup cron-jobb for commit and push repo"
  become: yes
  template:
    src: deploy_cron_commit_and_push_repo.cron.j2
    dest: "/etc/cron.d/commit_and_push-{{ webinstance.environment }}-{{ webinstance.name }}-{{ repo.name }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
   