---
# https://www.cyberciti.biz/faq/how-to-install-and-use-nginx-on-centos-8/
# https://github.com/ansible/ansible/issues/64852
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_managing_and_removing_user-space_components/removing-rhel-8-content_using-appstream

#- include_role:
#    name: dnf_module
#    tasks_from: install_package_from_module
#  vars:
#    dnf:
#      module_name: nginx
#      module_spec: "1.16"
#      packages:
#        - nginx

- name: "List enabled module (DNF)"
  become: yes
  shell:
    cmd: >-
      dnf module list --enabled {{ dnf.module_name }} | grep "^{{ dnf.module_name }}"
    warn: false # Ansible is warning for using dnf
  register: module_list_enabled
  changed_when: dnf.module_spec|string  not in module_list_enabled.stdout
  tags:
    - always

- name: "Uninstall present packages (DNF)"
  become: yes
  dnf:
    name: "{{ dnf.packages }}"
    state: absent
  when: dnf.module_spec|string not in module_list_enabled.stdout
  tags:
    - always

- name: "Reset module (DNF)"
  become: yes
  shell:
    cmd: "dnf module reset -y {{ dnf.module_name }}"
    warn: false # Ansible is warning for using dnf
  when: dnf.module_spec|string not in module_list_enabled.stdout
  tags:
    - always

- name: "Enable module (DNF)"
  become: yes
  shell:
    cmd: "dnf module enable -y {{ dnf.module_name }}:{{ dnf.module_spec }}"
    warn: false # Ansible is warning for using dnf
  when: dnf.module_spec|string not in module_list_enabled.stdout
  tags:
    - always

- name: "Install package (DNF)"
  become: yes
  yum:
    name: "{{ dnf.packages }}"
    state: present
  tags:
    - always
